# Generated by Django 4.2.27 on 2026-01-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
