# Generated by Django 4.2.27 on 2026-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='statement_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'statement_hash'], name='core_expens_user_id_750eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('statement_hash__isnull', False)), fields=('user', 'statement_hash'), name='uniq_expense_user_statement_hash'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('user', 'expense_date', 'amount', 'description', 'direction', 'source'), name='uniq_expense_user_day_amount_desc_dir_source'),
        ),
    ]
