# Generated by Django 4.2.27 on 2026-01-06 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_delete_income_appuser_created_at_appuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SALARY', 'SALARY'), ('FREELANCE', 'FREELANCE'), ('BUSINESS', 'BUSINESS'), ('RENTAL', 'RENTAL'), ('INTEREST', 'INTEREST'), ('OTHER', 'OTHER')], default='SALARY', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-income_date', '-id'],
                'indexes': [models.Index(fields=['user', 'income_date'], name='core_income_user_id_1d803f_idx'), models.Index(fields=['user', 'category'], name='core_income_user_id_bba173_idx')],
            },
        ),
    ]
