# Generated by Django 4.2.27 on 2026-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_expense_uniq_expense_user_statement_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='statement_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
