# Generated by Django 4.2.27 on 2026-01-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_statement_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='core_expens_user_id_1376dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='core_expens_user_id_a64772_idx',
        ),
    ]
