# Generated by Django 4.2.27 on 2026-01-06 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_savingsgoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsgoal',
            options={'ordering': ['-target_date', '-id']},
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('GIVEN', 'GIVEN'), ('TAKEN', 'TAKEN')], default='GIVEN', max_length=10)),
                ('person_name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ONGOING', 'ONGOING'), ('PAID', 'PAID')], default='ONGOING', max_length=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['user', 'loan_type'], name='core_loan_user_id_ca5cc5_idx'), models.Index(fields=['user', 'status'], name='core_loan_user_id_b1206b_idx')],
            },
        ),
    ]
