# Generated by Django 4.2.27 on 2026-01-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-id']},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'expense_date'], name='core_expens_user_id_1376dc_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='core_expens_user_id_a64772_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'statement_hash'], name='core_expens_user_id_750eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('statement_hash__isnull', False)), fields=('user', 'statement_hash'), name='uniq_expense_user_statement_hash'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('user', 'expense_date', 'amount', 'description', 'direction', 'source'), name='uniq_expense_user_day_amount_desc_dir_source'),
        ),
    ]
