# Generated by Django 4.2.27 on 2026-01-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expense',
            name='uniq_expense_user_statement_hash',
        ),
        migrations.RemoveConstraint(
            model_name='expense',
            name='uniq_expense_user_day_amount_desc_dir_source',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='core_expens_user_id_750eaf_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='statement_hash',
        ),
    ]
