# Generated by Django 4.2.27 on 2026-01-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_savingsgoal_options_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'start_date'], name='core_loan_user_id_658773_idx'),
        ),
        migrations.AddField(
            model_name='emergencyfund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emergencyfund',
            index=models.Index(fields=['user', 'created_at'], name='core_emerge_user_id_9d276c_idx'),
        ),
    ]
