# Generated by Django 4.2.27 on 2026-01-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emergencyfund_loan_title_alter_loan_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyfund',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='emergencyfund',
            name='core_emerge_user_id_9d276c_idx',
        ),
    ]
