# Generated by Django 4.2.27 on 2026-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_savingscontribution_notificationevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyfund',
            name='interval',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
