# Generated by Django 4.2.27 on 2026-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emergencyfund_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyfund',
            name='interval',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
