# Generated by Django 4.2.27 on 2026-01-10 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_emergencyfund_saved_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_interval', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='emergencyfund',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='core_income_user_id_1d803f_idx',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='core_income_user_id_bba173_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='core_loan_user_id_ca5cc5_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='core_loan_user_id_b1206b_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='core_loan_user_id_658773_idx',
        ),
        migrations.RemoveIndex(
            model_name='savingsgoal',
            name='core_saving_user_id_9750ff_idx',
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('FREELANCE', 'FREELANCE'), ('BUSINESS', 'BUSINESS'), ('RENTAL', 'RENTAL'), ('INTEREST', 'INTEREST'), ('OTHER', 'OTHER')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('GIVEN', 'GIVEN'), ('TAKEN', 'TAKEN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('PAID', 'PAID')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='insurancepolicy',
            unique_together={('user', 'policy_number')},
        ),
    ]
