# Generated by Django 4.2.27 on 2026-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emergencyfund_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyfund',
            name='last_contribution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyfund',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyfund',
            name='interval',
            field=models.CharField(default='monthly', max_length=20),
        ),
    ]
