# Generated by Django 4.2.27 on 2026-01-16 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_insurancepolicy_alter_emergencyfund_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant', models.CharField(blank=True, max_length=140, null=True)),
                ('category', models.CharField(db_index=True, default='Other', max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=80, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(db_index=True)),
                ('payment_mode', models.CharField(blank=True, max_length=30, null=True)),
                ('direction', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], default='DEBIT', max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'MANUAL'), ('OCR', 'OCR'), ('STATEMENT', 'STATEMENT')], default='MANUAL', max_length=20)),
                ('txn_id', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['user', 'expense_date'], name='core_expens_user_id_1376dc_idx'), models.Index(fields=['user', 'category'], name='core_expens_user_id_a64772_idx')],
            },
        ),
    ]
