# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_appuser_password_hash_appuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
