# Generated by Django 4.2.27 on 2026-01-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_appuser_user_id_alter_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_id',
        ),
    ]
